In [1]:
!nvidia-smi

Wed Dec 25 11:58:59 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 556.13                 Driver Version: 556.13         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650 Ti   WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   42C    P0             16W /   50W |     742MiB /   4096MiB |      4%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.1+cu118


## Introduction of Tensor

### Creating tensors

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim
scalar.shape

torch.Size([])

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([3,4])
vector

tensor([3, 4])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
matrix = torch.tensor([[5,6],[7,8]])
matrix

tensor([[5, 6],
        [7, 8]])

In [10]:
matrix.ndim


2

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
tensor.ndim

3

In [14]:
tensor.shape

torch.Size([1, 3, 3])

In [15]:
tensor[0][0][1]

tensor(2)

In [16]:
random = torch.rand([3,4])
random

tensor([[0.5194, 0.8785, 0.9930, 0.8879],
        [0.6528, 0.2086, 0.0057, 0.2791],
        [0.5898, 0.3269, 0.5392, 0.1503]])

In [17]:
zeros = torch.zeros(size = (3,225,225))
zeros


tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

In [18]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
ones.dtype

torch.float32

In [20]:
one_to_ten = torch.arange(start=1, end = 100, step = 2)
one_to_ten

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
        73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [21]:
zeros_like = torch.zeros_like(input= one_to_ten)
zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

In [3]:

tensor_multi =torch.tensor([1,2,3])   
tensor_multi + 10

tensor([11, 12, 13])

In [4]:
tensor_multi - 2

tensor([-1,  0,  1])

In [5]:
tensor_multi *8

tensor([ 8, 16, 24])

In [7]:
print(tensor_multi," * ", tensor_multi)
print(f"Equals to = {tensor_multi * tensor_multi}")

tensor([1, 2, 3])  *  tensor([1, 2, 3])
Equals to = tensor([1, 4, 9])


In [14]:
torch.matmul(tensor_multi, torch.tensor([6,3,2]))

tensor(18)

In [16]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]
                         ])
tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [26]:
tensor_B = torch.tensor([[7,8],
                         [3,4],
                         [6,7]
                         ])

tensor_B

tensor([[7, 8],
        [3, 4],
        [6, 7]])

In [27]:
tensor_A.shape , tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [28]:
tensor_B.T

tensor([[7, 3, 6],
        [8, 4, 7]])

In [31]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[23, 11, 20],
        [53, 25, 46],
        [83, 39, 72]])