### Torch 

* Torch contains the data-structure for multi dimensional tensors and define the mathematical operations over these tensors. 
* It provide many utilities for efficient serialize of tensors 


### Tensor

* Tensor is a mathematical object that can manipulate data into multiple dimension like vectors, scalars and metrics. 
* Tensor is widely popular in many fields such as Math, Physics, machine learning and computer science. 


In [1]:
import torch

In [11]:
x = torch.tensor([1,2,3])
torch.is_tensor(x)

True

In [12]:
y = torch.FloatStorage([1,2,4])
y

 1.0
 2.0
 4.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 3]

In [13]:
torch.is_storage(y)

True

In [17]:
torch.is_complex(x.type(torch.complex32))

C:\Users\2000a\AppData\Local\Temp\ipykernel_26856\1136912.py:1: UserWarning: ComplexHalf support is experimental and many operators don't support it yet. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\EmptyTensor.cpp:47.)
  torch.is_complex(x.type(torch.complex32))


True

In [18]:
y.dtype

torch.float32

In [27]:
tensor = torch.tensor([1,2,3])

torch.is_floating_point(tensor.type(torch.float32))

True

In [32]:
tensor

tensor([1, 2, 3])

In [36]:
torch.is_nonzero(torch.tensor([1]))

True

In [37]:
torch.set_default_dtype(torch.float64)

In [39]:
tensor.dtype

torch.int64

In [41]:
torch.get_default_dtype()

torch.float64

In [42]:
tens = torch.tensor([2,3,4])
tens.dtype

torch.int64

In [43]:
torch.get_default_device()

device(type='cpu')

In [44]:
x

tensor([1, 2, 3])

In [45]:
x.numel()

3

In [49]:
torch.set_printoptions(precision = 3)

torch.tensor([1.245567])

tensor([1.246])

In [50]:
i = torch.tensor([[1,2,3], [4,5,6]])
v = torch.tensor([7,8,9])
torch.sparse_coo_tensor(i, v, [2,3])

tensor(indices=tensor([[1, 2, 3],
                       [4, 5, 6]]),
       values=tensor([7, 8, 9]),
       size=(2, 3), nnz=3, layout=torch.sparse_coo)

In [51]:
a = torch.tensor([1,2,3])
b = torch.asarray(a)
b

tensor([1, 2, 3])

In [53]:
a.data_ptr == b.data_ptr

True

In [54]:
c = torch.asarray(a, copy=True)
c

tensor([1, 2, 3])

In [55]:
a.data_ptr == c.data_ptr

False

In [95]:
a = torch.tensor([1,2,3], dtype=torch.float32, requires_grad=True)
b = a ** 2 + 3 * a + 5
loss = b.sum()
loss.backward()


In [96]:
print(a.grad)

tensor([5., 7., 9.], dtype=torch.float32)


In [73]:
b

tensor([ 9., 15., 23.], dtype=torch.float32)

In [74]:
d = torch.asarray(a)

In [79]:
print(a)

tensor([3., 4., 5.], dtype=torch.float32)


In [97]:
import numpy as np

data = np.array([1,2,3])
data

array([1, 2, 3])

In [98]:
t1 = torch.as_tensor(data)
t1

tensor([1, 2, 3], dtype=torch.int32)

In [100]:
t1[0] = -1
t1

tensor([-1,  2,  3], dtype=torch.int32)

In [101]:
data

array([-1,  2,  3])

In [103]:
a = np.array([1,2,4])
t = torch.from_numpy(a)
t = torch.arange(3)
t

tensor([0, 1, 2])

In [104]:
t2 = torch.from_dlpack(t)
t2[:2] = -1
t2

tensor([-1, -1,  2])

In [105]:
t

tensor([-1, -1,  2])

In [111]:
zeros = torch.zeros_like(torch.tensor([1,2,3]))
zeros

tensor([0, 0, 0])

In [112]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [115]:
torch.ones_like(torch.rand(2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [117]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [125]:
torch.linspace(5,50,steps=12)

tensor([ 5.000,  9.091, 13.182, 17.273, 21.364, 25.455, 29.545, 33.636, 37.727,
        41.818, 45.909, 50.000])

In [127]:
torch.logspace(10, -10, steps = 5, base=2)

tensor([1.024e+03, 3.200e+01, 1.000e+00, 3.125e-02, 9.766e-04])

In [129]:
torch.eye(4,1)

tensor([[1.],
        [0.],
        [0.],
        [0.]])

In [130]:
torch.empty(2,3)

tensor([[1.024e+03, 3.200e+01, 1.000e+00],
        [3.125e-02, 9.766e-04, 0.000e+00]])

In [135]:
torch.empty_like(torch.empty((2,3), dtype=torch.int32))

tensor([[         0, 1072693248,          0],
        [1073741824,          0, 1074266112]], dtype=torch.int32)

In [137]:
torch.full((2,3),2)

tensor([[2, 2, 2],
        [2, 2, 2]])